# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_About(object):
    def setupUi(self, About):
        About.setObjectName("About")
        About.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(About)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_111 = QtWidgets.QLabel(About)
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.label_111.setFont(font)
        self.label_111.setObjectName("label_111")
        self.verticalLayout.addWidget(self.label_111)
        self.frame_18 = QtWidgets.QFrame(About)
        self.frame_18.setStyleSheet("QFrame {\n"
"    border-radius: 15px;\n"
"    background-color: rgb(212, 212, 255);\n"
"}\n"
"")
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.frame_18)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.deleteDB = QtWidgets.QPushButton(self.frame_18)
        self.deleteDB.setStyleSheet("\n"
"     height: 30px;\n"
"     box-sizing: border-box;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"")
        self.deleteDB.setObjectName("deleteDB")
        self.verticalLayout_2.addWidget(self.deleteDB)
        self.verticalLayout.addWidget(self.frame_18)

        self.retranslateUi(About)
        QtCore.QMetaObject.connectSlotsByName(About)

    def retranslateUi(self, About):
        _translate = QtCore.QCoreApplication.translate
        About.setWindowTitle(_translate("About", "Dialog"))
        self.label_111.setText(_translate("About", "О программе"))
        self.label.setText(_translate("About", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Авторы:</span></p><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Студенты ОМГТУ</span></p><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Ганев С.Ю.</span></p><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Ковалев Д.А.</span></p><p align=\"center\">2024 год</p></body></html>"))
        self.deleteDB.setText(_translate("About", "Сбросить базу данных"))
