# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'splash_screen_adaptive.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(1006, 638)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Main)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.mainWidget = QtWidgets.QWidget(Main)
        self.mainWidget.setObjectName("mainWidget")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.mainWidget)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.widget_10 = QtWidgets.QWidget(self.mainWidget)
        self.widget_10.setFocusPolicy(QtCore.Qt.NoFocus)
        self.widget_10.setStyleSheet("background-color:white;\n"
"border-radius: 15px;")
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.mainButton = QtWidgets.QPushButton(self.widget_10)
        self.mainButton.setStyleSheet("QPushButton{\n"
"      height: 30px;\n"
"      box-sizing: border-box;\n"
"     background-color: rgb(212, 212, 255);\n"
"      border-radius: 5px;\n"
"    font-weight: bold;\n"
"}")
        self.mainButton.setObjectName("mainButton")
        self.verticalLayout_2.addWidget(self.mainButton)
        self.mealButton = QtWidgets.QPushButton(self.widget_10)
        self.mealButton.setStyleSheet("QPushButton{\n"
"      height: 30px;\n"
"      box-sizing: border-box;\n"
"     background-color: rgb(212, 212, 255);\n"
"      border-radius: 5px;\n"
"    font-weight: bold;\n"
"}")
        self.mealButton.setObjectName("mealButton")
        self.verticalLayout_2.addWidget(self.mealButton)
        self.hungerButton = QtWidgets.QPushButton(self.widget_10)
        self.hungerButton.setMinimumSize(QtCore.QSize(110, 30))
        self.hungerButton.setMaximumSize(QtCore.QSize(110, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.hungerButton.setFont(font)
        self.hungerButton.setStyleSheet("QPushButton{\n"
"      height: 30px;\n"
"      box-sizing: border-box;\n"
"     background-color: rgb(212, 212, 255);\n"
"      border-radius: 5px;\n"
"    font-weight: bold;\n"
"}")
        self.hungerButton.setObjectName("hungerButton")
        self.verticalLayout_2.addWidget(self.hungerButton)
        self.resultButton = QtWidgets.QPushButton(self.widget_10)
        self.resultButton.setStyleSheet("QPushButton{\n"
"      height: 30px;\n"
"      box-sizing: border-box;\n"
"     background-color: rgb(212, 212, 255);\n"
"      border-radius: 5px;\n"
"    font-weight: bold;\n"
"}")
        self.resultButton.setObjectName("resultButton")
        self.verticalLayout_2.addWidget(self.resultButton)
        spacerItem = QtWidgets.QSpacerItem(20, 316, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.switchAccount = QtWidgets.QPushButton(self.widget_10)
        self.switchAccount.setStyleSheet("QPushButton{\n"
"      height: 30px;\n"
"      box-sizing: border-box;\n"
"     background-color: rgb(212, 212, 255);\n"
"      border-radius: 5px;\n"
"    font-weight: bold;\n"
"}")
        self.switchAccount.setObjectName("switchAccount")
        self.verticalLayout_2.addWidget(self.switchAccount)
        self.aboutButton = QtWidgets.QPushButton(self.widget_10)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.aboutButton.setFont(font)
        self.aboutButton.setStyleSheet("QPushButton{\n"
"      height: 30px;\n"
"      box-sizing: border-box;\n"
"      border-radius: 5px;\n"
"}")
        self.aboutButton.setObjectName("aboutButton")
        self.verticalLayout_2.addWidget(self.aboutButton)
        self.horizontalLayout_9.addWidget(self.widget_10)
        self.widget_11 = QtWidgets.QWidget(self.mainWidget)
        self.widget_11.setStyleSheet("background-color:white;\n"
"border-radius: 15px;")
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_11)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.stackedWidgetMain = QtWidgets.QStackedWidget(self.widget_11)
        self.stackedWidgetMain.setToolTip("")
        self.stackedWidgetMain.setObjectName("stackedWidgetMain")
        self.mealPage = QtWidgets.QWidget()
        self.mealPage.setObjectName("mealPage")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.mealPage)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout()
        self.verticalLayout_34.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.verticalLayout_38 = QtWidgets.QVBoxLayout()
        self.verticalLayout_38.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.label_58 = QtWidgets.QLabel(self.mealPage)
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.label_58.setFont(font)
        self.label_58.setObjectName("label_58")
        self.verticalLayout_38.addWidget(self.label_58)
        self.verticalLayout_34.addLayout(self.verticalLayout_38)
        self.verticalLayout_39 = QtWidgets.QVBoxLayout()
        self.verticalLayout_39.setObjectName("verticalLayout_39")
        self.frame_12 = QtWidgets.QFrame(self.mealPage)
        self.frame_12.setStyleSheet("border-radius: 15px;\n"
"background-color: rgb(212, 212, 255);\n"
"\n"
"")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.meal_breakButton = QtWidgets.QPushButton(self.frame_12)
        self.meal_breakButton.setStyleSheet("\n"
"      height: 50px;\n"
"      width:200px;\n"
"      box-sizing: border-box;\n"
"     background-color: white;\n"
"      border-radius: 5px;\n"
"")
        self.meal_breakButton.setObjectName("meal_breakButton")
        self.gridLayout_3.addWidget(self.meal_breakButton, 0, 0, 1, 1)
        self.meal_dinnerButton = QtWidgets.QPushButton(self.frame_12)
        self.meal_dinnerButton.setStyleSheet("QPushButton{\n"
"      height: 50px;\n"
"      width:200px;\n"
"      box-sizing: border-box;\n"
"     background-color: white;\n"
"      border-radius: 5px;\n"
"}")
        self.meal_dinnerButton.setObjectName("meal_dinnerButton")
        self.gridLayout_3.addWidget(self.meal_dinnerButton, 1, 0, 1, 1)
        self.meal_addBreakButton = QtWidgets.QPushButton(self.frame_12)
        self.meal_addBreakButton.setStyleSheet("      height: 50px;\n"
"      width:50px;\n"
"      box-sizing: border-box;\n"
"     background-color: white;\n"
"      border-radius: 5px;")
        self.meal_addBreakButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/img/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.meal_addBreakButton.setIcon(icon)
        self.meal_addBreakButton.setIconSize(QtCore.QSize(25, 25))
        self.meal_addBreakButton.setObjectName("meal_addBreakButton")
        self.gridLayout_3.addWidget(self.meal_addBreakButton, 0, 1, 1, 1)
        self.meal_addDinnerButton = QtWidgets.QPushButton(self.frame_12)
        self.meal_addDinnerButton.setStyleSheet("      height: 50px;\n"
"      width:50px;\n"
"      box-sizing: border-box;\n"
"     background-color: white;\n"
"      border-radius: 5px;")
        self.meal_addDinnerButton.setText("")
        self.meal_addDinnerButton.setIcon(icon)
        self.meal_addDinnerButton.setIconSize(QtCore.QSize(25, 25))
        self.meal_addDinnerButton.setObjectName("meal_addDinnerButton")
        self.gridLayout_3.addWidget(self.meal_addDinnerButton, 1, 1, 1, 1)
        self.meal_emealButton = QtWidgets.QPushButton(self.frame_12)
        self.meal_emealButton.setStyleSheet("QPushButton{\n"
"      height: 50px;\n"
"      width:200px;\n"
"      box-sizing: border-box;\n"
"     background-color: white;\n"
"      border-radius: 5px;\n"
"}")
        self.meal_emealButton.setObjectName("meal_emealButton")
        self.gridLayout_3.addWidget(self.meal_emealButton, 2, 0, 1, 1)
        self.meal_addSnackButton = QtWidgets.QPushButton(self.frame_12)
        self.meal_addSnackButton.setStyleSheet("      height: 50px;\n"
"      width:2px;\n"
"      box-sizing: border-box;\n"
"     background-color: white;\n"
"      border-radius: 5px;")
        self.meal_addSnackButton.setText("")
        self.meal_addSnackButton.setIcon(icon)
        self.meal_addSnackButton.setIconSize(QtCore.QSize(25, 25))
        self.meal_addSnackButton.setObjectName("meal_addSnackButton")
        self.gridLayout_3.addWidget(self.meal_addSnackButton, 3, 1, 1, 1)
        self.meal_snackButton = QtWidgets.QPushButton(self.frame_12)
        self.meal_snackButton.setStyleSheet("QPushButton{\n"
"      height: 50px;\n"
"      width:200px;\n"
"      box-sizing: border-box;\n"
"     background-color: white;\n"
"      border-radius: 5px;\n"
"}")
        self.meal_snackButton.setObjectName("meal_snackButton")
        self.gridLayout_3.addWidget(self.meal_snackButton, 3, 0, 1, 1)
        self.meal_addEmealButton = QtWidgets.QPushButton(self.frame_12)
        self.meal_addEmealButton.setStyleSheet("      height: 50px;\n"
"      width:50px;\n"
"      box-sizing: border-box;\n"
"     background-color: white;\n"
"      border-radius: 5px;")
        self.meal_addEmealButton.setText("")
        self.meal_addEmealButton.setIcon(icon)
        self.meal_addEmealButton.setIconSize(QtCore.QSize(25, 25))
        self.meal_addEmealButton.setObjectName("meal_addEmealButton")
        self.gridLayout_3.addWidget(self.meal_addEmealButton, 2, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.stackedWidgetMeal = QtWidgets.QStackedWidget(self.frame_12)
        self.stackedWidgetMeal.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.stackedWidgetMeal.setAutoFillBackground(False)
        self.stackedWidgetMeal.setStyleSheet("QStackerWidget{\n"
"    background-color: rgb(212, 212, 255);\n"
"}")
        self.stackedWidgetMeal.setObjectName("stackedWidgetMeal")
        self.meal_breakPage = QtWidgets.QWidget()
        self.meal_breakPage.setObjectName("meal_breakPage")
        self.horizontalLayout_50 = QtWidgets.QHBoxLayout(self.meal_breakPage)
        self.horizontalLayout_50.setObjectName("horizontalLayout_50")
        self.verticalLayout_72 = QtWidgets.QVBoxLayout()
        self.verticalLayout_72.setObjectName("verticalLayout_72")
        self.label = QtWidgets.QLabel(self.meal_breakPage)
        self.label.setObjectName("label")
        self.verticalLayout_72.addWidget(self.label)
        self.breakName = QtWidgets.QLabel(self.meal_breakPage)
        self.breakName.setStyleSheet(" font-size:18pt;")
        self.breakName.setObjectName("breakName")
        self.verticalLayout_72.addWidget(self.breakName)
        self.breakCalories = QtWidgets.QLabel(self.meal_breakPage)
        self.breakCalories.setStyleSheet(" font-size:18pt;")
        self.breakCalories.setObjectName("breakCalories")
        self.verticalLayout_72.addWidget(self.breakCalories)
        self.breakProtein = QtWidgets.QLabel(self.meal_breakPage)
        self.breakProtein.setStyleSheet(" font-size:18pt;")
        self.breakProtein.setObjectName("breakProtein")
        self.verticalLayout_72.addWidget(self.breakProtein)
        self.breakFat = QtWidgets.QLabel(self.meal_breakPage)
        self.breakFat.setStyleSheet(" font-size:18pt;")
        self.breakFat.setObjectName("breakFat")
        self.verticalLayout_72.addWidget(self.breakFat)
        self.breakCarbo = QtWidgets.QLabel(self.meal_breakPage)
        self.breakCarbo.setStyleSheet(" font-size:18pt;")
        self.breakCarbo.setObjectName("breakCarbo")
        self.verticalLayout_72.addWidget(self.breakCarbo)
        self.horizontalLayout_50.addLayout(self.verticalLayout_72)
        self.stackedWidgetMeal.addWidget(self.meal_breakPage)
        self.meal_dinnerPage = QtWidgets.QWidget()
        self.meal_dinnerPage.setObjectName("meal_dinnerPage")
        self.horizontalLayout_51 = QtWidgets.QHBoxLayout(self.meal_dinnerPage)
        self.horizontalLayout_51.setObjectName("horizontalLayout_51")
        self.verticalLayout_40 = QtWidgets.QVBoxLayout()
        self.verticalLayout_40.setObjectName("verticalLayout_40")
        self.label_3 = QtWidgets.QLabel(self.meal_dinnerPage)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_40.addWidget(self.label_3)
        self.dinnerName = QtWidgets.QLabel(self.meal_dinnerPage)
        self.dinnerName.setStyleSheet(" font-size:18pt;")
        self.dinnerName.setObjectName("dinnerName")
        self.verticalLayout_40.addWidget(self.dinnerName)
        self.dinnerCalories = QtWidgets.QLabel(self.meal_dinnerPage)
        self.dinnerCalories.setStyleSheet(" font-size:18pt;")
        self.dinnerCalories.setObjectName("dinnerCalories")
        self.verticalLayout_40.addWidget(self.dinnerCalories)
        self.dinnerProtein = QtWidgets.QLabel(self.meal_dinnerPage)
        self.dinnerProtein.setStyleSheet(" font-size:18pt;")
        self.dinnerProtein.setObjectName("dinnerProtein")
        self.verticalLayout_40.addWidget(self.dinnerProtein)
        self.dinnerFat = QtWidgets.QLabel(self.meal_dinnerPage)
        self.dinnerFat.setStyleSheet(" font-size:18pt;")
        self.dinnerFat.setObjectName("dinnerFat")
        self.verticalLayout_40.addWidget(self.dinnerFat)
        self.dinnerCarbo = QtWidgets.QLabel(self.meal_dinnerPage)
        self.dinnerCarbo.setStyleSheet(" font-size:18pt;")
        self.dinnerCarbo.setObjectName("dinnerCarbo")
        self.verticalLayout_40.addWidget(self.dinnerCarbo)
        self.horizontalLayout_51.addLayout(self.verticalLayout_40)
        self.stackedWidgetMeal.addWidget(self.meal_dinnerPage)
        self.meal_emealPage = QtWidgets.QWidget()
        self.meal_emealPage.setObjectName("meal_emealPage")
        self.horizontalLayout_52 = QtWidgets.QHBoxLayout(self.meal_emealPage)
        self.horizontalLayout_52.setObjectName("horizontalLayout_52")
        self.verticalLayout_42 = QtWidgets.QVBoxLayout()
        self.verticalLayout_42.setObjectName("verticalLayout_42")
        self.label_4 = QtWidgets.QLabel(self.meal_emealPage)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_42.addWidget(self.label_4)
        self.emealName = QtWidgets.QLabel(self.meal_emealPage)
        self.emealName.setStyleSheet(" font-size:18pt;")
        self.emealName.setObjectName("emealName")
        self.verticalLayout_42.addWidget(self.emealName)
        self.emealCalories = QtWidgets.QLabel(self.meal_emealPage)
        self.emealCalories.setStyleSheet(" font-size:18pt;")
        self.emealCalories.setObjectName("emealCalories")
        self.verticalLayout_42.addWidget(self.emealCalories)
        self.emealProtein = QtWidgets.QLabel(self.meal_emealPage)
        self.emealProtein.setStyleSheet(" font-size:18pt;")
        self.emealProtein.setObjectName("emealProtein")
        self.verticalLayout_42.addWidget(self.emealProtein)
        self.emealFat = QtWidgets.QLabel(self.meal_emealPage)
        self.emealFat.setStyleSheet(" font-size:18pt;")
        self.emealFat.setObjectName("emealFat")
        self.verticalLayout_42.addWidget(self.emealFat)
        self.emealCarbo = QtWidgets.QLabel(self.meal_emealPage)
        self.emealCarbo.setStyleSheet(" font-size:18pt;")
        self.emealCarbo.setObjectName("emealCarbo")
        self.verticalLayout_42.addWidget(self.emealCarbo)
        self.horizontalLayout_52.addLayout(self.verticalLayout_42)
        self.stackedWidgetMeal.addWidget(self.meal_emealPage)
        self.meal_snackPage = QtWidgets.QWidget()
        self.meal_snackPage.setObjectName("meal_snackPage")
        self.horizontalLayout_53 = QtWidgets.QHBoxLayout(self.meal_snackPage)
        self.horizontalLayout_53.setObjectName("horizontalLayout_53")
        self.verticalLayout_43 = QtWidgets.QVBoxLayout()
        self.verticalLayout_43.setObjectName("verticalLayout_43")
        self.label_5 = QtWidgets.QLabel(self.meal_snackPage)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_43.addWidget(self.label_5)
        self.snackName = QtWidgets.QLabel(self.meal_snackPage)
        self.snackName.setStyleSheet(" font-size:18pt;")
        self.snackName.setObjectName("snackName")
        self.verticalLayout_43.addWidget(self.snackName)
        self.snackCalories = QtWidgets.QLabel(self.meal_snackPage)
        self.snackCalories.setStyleSheet(" font-size:18pt;")
        self.snackCalories.setObjectName("snackCalories")
        self.verticalLayout_43.addWidget(self.snackCalories)
        self.snackProtein = QtWidgets.QLabel(self.meal_snackPage)
        self.snackProtein.setStyleSheet(" font-size:18pt;")
        self.snackProtein.setObjectName("snackProtein")
        self.verticalLayout_43.addWidget(self.snackProtein)
        self.snackFat = QtWidgets.QLabel(self.meal_snackPage)
        self.snackFat.setStyleSheet(" font-size:18pt;")
        self.snackFat.setObjectName("snackFat")
        self.verticalLayout_43.addWidget(self.snackFat)
        self.snackCarbo = QtWidgets.QLabel(self.meal_snackPage)
        self.snackCarbo.setStyleSheet(" font-size:18pt;")
        self.snackCarbo.setObjectName("snackCarbo")
        self.verticalLayout_43.addWidget(self.snackCarbo)
        self.horizontalLayout_53.addLayout(self.verticalLayout_43)
        self.stackedWidgetMeal.addWidget(self.meal_snackPage)
        self.horizontalLayout.addWidget(self.stackedWidgetMeal)
        self.horizontalLayout.setStretch(2, 200)
        self.verticalLayout_39.addWidget(self.frame_12)
        self.verticalLayout_39.setStretch(0, 1)
        self.verticalLayout_34.addLayout(self.verticalLayout_39)
        self.verticalLayout_34.setStretch(1, 1)
        self.horizontalLayout_25.addLayout(self.verticalLayout_34)
        self.stackedWidgetMain.addWidget(self.mealPage)
        self.hungerPage = QtWidgets.QWidget()
        self.hungerPage.setObjectName("hungerPage")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.hungerPage)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.verticalLayout_44 = QtWidgets.QVBoxLayout()
        self.verticalLayout_44.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_44.setObjectName("verticalLayout_44")
        self.verticalLayout_45 = QtWidgets.QVBoxLayout()
        self.verticalLayout_45.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_45.setObjectName("verticalLayout_45")
        self.label_84 = QtWidgets.QLabel(self.hungerPage)
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.label_84.setFont(font)
        self.label_84.setObjectName("label_84")
        self.verticalLayout_45.addWidget(self.label_84)
        self.verticalLayout_44.addLayout(self.verticalLayout_45)
        self.verticalLayout_46 = QtWidgets.QVBoxLayout()
        self.verticalLayout_46.setObjectName("verticalLayout_46")
        self.frame_13 = QtWidgets.QFrame(self.hungerPage)
        self.frame_13.setStyleSheet("QFrame {\n"
"    border-radius: 15px;\n"
"    background-color: rgb(212, 212, 255);\n"
"}\n"
"")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.verticalLayout_47 = QtWidgets.QVBoxLayout()
        self.verticalLayout_47.setObjectName("verticalLayout_47")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_47.addItem(spacerItem2)
        self.frame_14 = QtWidgets.QFrame(self.frame_13)
        self.frame_14.setStyleSheet("QFrame {\n"
"    border-radius: 15px;\n"
"    background-color:white;\n"
"}\n"
"")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.verticalLayout_48 = QtWidgets.QVBoxLayout()
        self.verticalLayout_48.setObjectName("verticalLayout_48")
        self.label_85 = QtWidgets.QLabel(self.frame_14)
        self.label_85.setObjectName("label_85")
        self.verticalLayout_48.addWidget(self.label_85)
        self.label_86 = QtWidgets.QLabel(self.frame_14)
        self.label_86.setObjectName("label_86")
        self.verticalLayout_48.addWidget(self.label_86)
        self.label_87 = QtWidgets.QLabel(self.frame_14)
        self.label_87.setObjectName("label_87")
        self.verticalLayout_48.addWidget(self.label_87)
        self.horizontalLayout_31.addLayout(self.verticalLayout_48)
        self.verticalLayout_47.addWidget(self.frame_14)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_47.addItem(spacerItem3)
        self.horizontalLayout_30.addLayout(self.verticalLayout_47)
        self.verticalLayout_49 = QtWidgets.QVBoxLayout()
        self.verticalLayout_49.setObjectName("verticalLayout_49")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"      height: 50px;\n"
"      box-sizing: border-box;\n"
"     background-color: white;\n"
"      border-radius: 5px;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_49.addWidget(self.pushButton_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_49.addItem(spacerItem4)
        self.horizontalLayout_30.addLayout(self.verticalLayout_49)
        self.horizontalLayout_29.addLayout(self.horizontalLayout_30)
        self.verticalLayout_46.addWidget(self.frame_13)
        self.verticalLayout_44.addLayout(self.verticalLayout_46)
        self.verticalLayout_44.setStretch(1, 1)
        self.horizontalLayout_28.addLayout(self.verticalLayout_44)
        self.stackedWidgetMain.addWidget(self.hungerPage)
        self.resultPage = QtWidgets.QWidget()
        self.resultPage.setObjectName("resultPage")
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout(self.resultPage)
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.verticalLayout_58 = QtWidgets.QVBoxLayout()
        self.verticalLayout_58.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_58.setObjectName("verticalLayout_58")
        self.verticalLayout_59 = QtWidgets.QVBoxLayout()
        self.verticalLayout_59.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_59.setObjectName("verticalLayout_59")
        self.label_107 = QtWidgets.QLabel(self.resultPage)
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.label_107.setFont(font)
        self.label_107.setObjectName("label_107")
        self.verticalLayout_59.addWidget(self.label_107)
        self.verticalLayout_58.addLayout(self.verticalLayout_59)
        self.verticalLayout_60 = QtWidgets.QVBoxLayout()
        self.verticalLayout_60.setObjectName("verticalLayout_60")
        self.frame_17 = QtWidgets.QFrame(self.resultPage)
        self.frame_17.setStyleSheet("QFrame {\n"
"    border-radius: 15px;\n"
"    background-color: rgb(212, 212, 255);\n"
"}\n"
"")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_61 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_61.setContentsMargins(-1, 9, -1, -1)
        self.verticalLayout_61.setObjectName("verticalLayout_61")
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.verticalLayout_62 = QtWidgets.QVBoxLayout()
        self.verticalLayout_62.setObjectName("verticalLayout_62")
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_62.addItem(spacerItem5)
        self.totalCalories = QtWidgets.QLabel(self.frame_17)
        self.totalCalories.setStyleSheet(" font-size:16pt")
        self.totalCalories.setObjectName("totalCalories")
        self.verticalLayout_62.addWidget(self.totalCalories)
        self.totalProtein = QtWidgets.QLabel(self.frame_17)
        self.totalProtein.setStyleSheet(" font-size:16pt")
        self.totalProtein.setObjectName("totalProtein")
        self.verticalLayout_62.addWidget(self.totalProtein)
        self.totalFat = QtWidgets.QLabel(self.frame_17)
        self.totalFat.setStyleSheet(" font-size:16pt")
        self.totalFat.setObjectName("totalFat")
        self.verticalLayout_62.addWidget(self.totalFat)
        self.totalCarbo = QtWidgets.QLabel(self.frame_17)
        self.totalCarbo.setStyleSheet(" font-size:16pt")
        self.totalCarbo.setObjectName("totalCarbo")
        self.verticalLayout_62.addWidget(self.totalCarbo)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_62.addItem(spacerItem6)
        self.horizontalLayout_42.addLayout(self.verticalLayout_62)
        self.verticalLayout_63 = QtWidgets.QVBoxLayout()
        self.verticalLayout_63.setObjectName("verticalLayout_63")
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_63.addItem(spacerItem7)
        self.label_6 = QtWidgets.QLabel(self.frame_17)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_63.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.frame_17)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_63.addWidget(self.label_7)
        self.congrats = QtWidgets.QLabel(self.frame_17)
        self.congrats.setStyleSheet("font-size:36pt; \n"
"font-weight :600;\n"
"text-align: center;")
        self.congrats.setObjectName("congrats")
        self.verticalLayout_63.addWidget(self.congrats)
        self.label_8 = QtWidgets.QLabel(self.frame_17)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_63.addWidget(self.label_8)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_63.addItem(spacerItem8)
        self.horizontalLayout_42.addLayout(self.verticalLayout_63)
        self.verticalLayout_61.addLayout(self.horizontalLayout_42)
        self.verticalLayout_60.addWidget(self.frame_17)
        self.verticalLayout_64 = QtWidgets.QVBoxLayout()
        self.verticalLayout_64.setObjectName("verticalLayout_64")
        self.verticalLayout_60.addLayout(self.verticalLayout_64)
        self.verticalLayout_60.setStretch(0, 1)
        self.verticalLayout_58.addLayout(self.verticalLayout_60)
        self.horizontalLayout_41.addLayout(self.verticalLayout_58)
        self.stackedWidgetMain.addWidget(self.resultPage)
        self.mainPage = QtWidgets.QWidget()
        self.mainPage.setObjectName("mainPage")
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout(self.mainPage)
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.verticalLayout_65 = QtWidgets.QVBoxLayout()
        self.verticalLayout_65.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_65.setObjectName("verticalLayout_65")
        self.verticalLayout_66 = QtWidgets.QVBoxLayout()
        self.verticalLayout_66.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_66.setObjectName("verticalLayout_66")
        self.label_111 = QtWidgets.QLabel(self.mainPage)
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.label_111.setFont(font)
        self.label_111.setObjectName("label_111")
        self.verticalLayout_66.addWidget(self.label_111)
        self.welcomeUser = QtWidgets.QLabel(self.mainPage)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.welcomeUser.setFont(font)
        self.welcomeUser.setObjectName("welcomeUser")
        self.verticalLayout_66.addWidget(self.welcomeUser)
        self.verticalLayout_65.addLayout(self.verticalLayout_66)
        self.verticalLayout_67 = QtWidgets.QVBoxLayout()
        self.verticalLayout_67.setObjectName("verticalLayout_67")
        self.frame_18 = QtWidgets.QFrame(self.mainPage)
        self.frame_18.setStyleSheet("QFrame {\n"
"    border-radius: 15px;\n"
"    background-color: rgb(212, 212, 255);\n"
"}\n"
"")
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_68 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_68.setContentsMargins(-1, 9, -1, -1)
        self.verticalLayout_68.setObjectName("verticalLayout_68")
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.verticalLayout_69 = QtWidgets.QVBoxLayout()
        self.verticalLayout_69.setObjectName("verticalLayout_69")
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_69.addItem(spacerItem9)
        self.PPLabel = QtWidgets.QLabel(self.frame_18)
        self.PPLabel.setObjectName("PPLabel")
        self.verticalLayout_69.addWidget(self.PPLabel)
        self.TrainingLabel = QtWidgets.QLabel(self.frame_18)
        self.TrainingLabel.setObjectName("TrainingLabel")
        self.verticalLayout_69.addWidget(self.TrainingLabel)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_69.addItem(spacerItem10)
        self.horizontalLayout_44.addLayout(self.verticalLayout_69)
        self.frame_19 = QtWidgets.QFrame(self.frame_18)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_45 = QtWidgets.QHBoxLayout(self.frame_19)
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.verticalLayout_70 = QtWidgets.QVBoxLayout()
        self.verticalLayout_70.setObjectName("verticalLayout_70")
        self.frame_20 = QtWidgets.QFrame(self.frame_19)
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.CircularProgressBar = QtWidgets.QFrame(self.frame_20)
        self.CircularProgressBar.setGeometry(QtCore.QRect(120, 70, 160, 161))
        self.CircularProgressBar.setStyleSheet("QFrame{\n"
"    border-radius: 80px;\n"
"    background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0.749 rgba(0, 0, 0, 0), stop:0.75 rgba(255, 255, 255, 255));\n"
"}")
        self.CircularProgressBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.CircularProgressBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.CircularProgressBar.setObjectName("CircularProgressBar")
        self.CircularProgressBar1 = QtWidgets.QFrame(self.CircularProgressBar)
        self.CircularProgressBar1.setGeometry(QtCore.QRect(20, 20, 121, 121))
        self.CircularProgressBar1.setStyleSheet("QFrame{\n"
"    border-radius: 60px;\n"
"    background-color: rgb(212, 212, 255);\n"
"}")
        self.CircularProgressBar1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.CircularProgressBar1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.CircularProgressBar1.setObjectName("CircularProgressBar1")
        self.verticalLayout_70.addWidget(self.frame_20)
        self.label_113 = QtWidgets.QLabel(self.frame_19)
        self.label_113.setObjectName("label_113")
        self.verticalLayout_70.addWidget(self.label_113)
        self.verticalLayout_70.setStretch(0, 1)
        self.horizontalLayout_45.addLayout(self.verticalLayout_70)
        self.horizontalLayout_44.addWidget(self.frame_19)
        self.verticalLayout_68.addLayout(self.horizontalLayout_44)
        self.verticalLayout_67.addWidget(self.frame_18)
        self.verticalLayout_71 = QtWidgets.QVBoxLayout()
        self.verticalLayout_71.setObjectName("verticalLayout_71")
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_46.addItem(spacerItem11)
        self.label_114 = QtWidgets.QLabel(self.mainPage)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_114.setFont(font)
        self.label_114.setObjectName("label_114")
        self.horizontalLayout_46.addWidget(self.label_114)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_46.addItem(spacerItem12)
        self.label_115 = QtWidgets.QLabel(self.mainPage)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_115.setFont(font)
        self.label_115.setObjectName("label_115")
        self.horizontalLayout_46.addWidget(self.label_115)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_46.addItem(spacerItem13)
        self.label_116 = QtWidgets.QLabel(self.mainPage)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_116.setFont(font)
        self.label_116.setObjectName("label_116")
        self.horizontalLayout_46.addWidget(self.label_116)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_46.addItem(spacerItem14)
        self.verticalLayout_71.addLayout(self.horizontalLayout_46)
        self.horizontalLayout_47 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_47.setObjectName("horizontalLayout_47")
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_47.addItem(spacerItem15)
        self.progressBar_Protein = QtWidgets.QProgressBar(self.mainPage)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.progressBar_Protein.setFont(font)
        self.progressBar_Protein.setStyleSheet("QProgressBar {\n"
"    background-color: white;\n"
"    border-radius: 10px;\n"
"    color: black;\n"
"    text-align: center;\n"
"  \n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"    border-radius: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(156, 164, 219, 255), stop:1 rgba(173, 200, 214, 255))\n"
"}")
        self.progressBar_Protein.setProperty("value", 100)
        self.progressBar_Protein.setObjectName("progressBar_Protein")
        self.horizontalLayout_47.addWidget(self.progressBar_Protein)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_47.addItem(spacerItem16)
        self.progressBar_Fat = QtWidgets.QProgressBar(self.mainPage)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.progressBar_Fat.setFont(font)
        self.progressBar_Fat.setStyleSheet("QProgressBar {\n"
"    background-color: white;\n"
"    border-radius: 10px;\n"
"    color: black;\n"
"    text-align: center;\n"
"  \n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"    border-radius: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(156, 164, 219, 255), stop:1 rgba(173, 200, 214, 255))\n"
"}")
        self.progressBar_Fat.setProperty("value", 50)
        self.progressBar_Fat.setObjectName("progressBar_Fat")
        self.horizontalLayout_47.addWidget(self.progressBar_Fat)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_47.addItem(spacerItem17)
        self.progressBar_Carbohydrates = QtWidgets.QProgressBar(self.mainPage)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.progressBar_Carbohydrates.setFont(font)
        self.progressBar_Carbohydrates.setStyleSheet("QProgressBar {\n"
"    background-color: white;\n"
"    border-radius: 10px;\n"
"    color: black;\n"
"    text-align: center;\n"
"  \n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"    border-radius: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(156, 164, 219, 255), stop:1 rgba(173, 200, 214, 255))\n"
"}")
        self.progressBar_Carbohydrates.setProperty("value", 0)
        self.progressBar_Carbohydrates.setObjectName("progressBar_Carbohydrates")
        self.horizontalLayout_47.addWidget(self.progressBar_Carbohydrates)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_47.addItem(spacerItem18)
        self.verticalLayout_71.addLayout(self.horizontalLayout_47)
        self.verticalLayout_67.addLayout(self.verticalLayout_71)
        self.verticalLayout_67.setStretch(0, 1)
        self.verticalLayout_65.addLayout(self.verticalLayout_67)
        self.verticalLayout_65.setStretch(1, 1)
        self.horizontalLayout_43.addLayout(self.verticalLayout_65)
        self.stackedWidgetMain.addWidget(self.mainPage)
        self.addPage = QtWidgets.QWidget()
        self.addPage.setObjectName("addPage")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.addPage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_117 = QtWidgets.QLabel(self.addPage)
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.label_117.setFont(font)
        self.label_117.setObjectName("label_117")
        self.horizontalLayout_12.addWidget(self.label_117)
        self.verticalLayout_8.addLayout(self.horizontalLayout_12)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget_22 = QtWidgets.QWidget(self.addPage)
        self.widget_22.setStyleSheet("border-radius: 15px;\n"
"background-color: rgb(212, 212, 255);\n"
"\n"
"")
        self.widget_22.setObjectName("widget_22")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_22)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.widget_22)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem19)
        self.lineEdit = QtWidgets.QLineEdit(self.widget_22)
        self.lineEdit.setStyleSheet("height: 50px;\n"
"background-color:white;\n"
"border-radius:5px;\n"
"border: 2px solid gray;\n"
"font: 30pt;")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_6.addWidget(self.lineEdit)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.add_calorieLine_ = QtWidgets.QLineEdit(self.widget_22)
        self.add_calorieLine_.setStyleSheet("height: 50px;\n"
"background-color:white;\n"
"border-radius:5px;\n"
"border: 2px solid gray;\n"
"font: 30pt;")
        self.add_calorieLine_.setText("")
        self.add_calorieLine_.setAlignment(QtCore.Qt.AlignCenter)
        self.add_calorieLine_.setObjectName("add_calorieLine_")
        self.horizontalLayout_10.addWidget(self.add_calorieLine_)
        self.add_proteinLine_ = QtWidgets.QLineEdit(self.widget_22)
        self.add_proteinLine_.setStyleSheet("height: 50px;\n"
"background-color:white;\n"
"border-radius:5px;\n"
"border: 2px solid gray;\n"
"font: 30pt;")
        self.add_proteinLine_.setText("")
        self.add_proteinLine_.setAlignment(QtCore.Qt.AlignCenter)
        self.add_proteinLine_.setObjectName("add_proteinLine_")
        self.horizontalLayout_10.addWidget(self.add_proteinLine_)
        self.add_fatLine_ = QtWidgets.QLineEdit(self.widget_22)
        self.add_fatLine_.setStyleSheet("height: 50px;\n"
"background-color:white;\n"
"border-radius:5px;\n"
"border: 2px solid gray;\n"
"font: 30pt;")
        self.add_fatLine_.setText("")
        self.add_fatLine_.setAlignment(QtCore.Qt.AlignCenter)
        self.add_fatLine_.setDragEnabled(False)
        self.add_fatLine_.setObjectName("add_fatLine_")
        self.horizontalLayout_10.addWidget(self.add_fatLine_)
        self.add_chLine_ = QtWidgets.QLineEdit(self.widget_22)
        self.add_chLine_.setStyleSheet("height: 50px;\n"
"background-color:white;\n"
"border-radius:5px;\n"
"border: 2px solid gray;\n"
"font: 30pt;")
        self.add_chLine_.setText("")
        self.add_chLine_.setAlignment(QtCore.Qt.AlignCenter)
        self.add_chLine_.setObjectName("add_chLine_")
        self.horizontalLayout_10.addWidget(self.add_chLine_)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem20)
        self.add_addMealButton = QtWidgets.QPushButton(self.widget_22)
        self.add_addMealButton.setStyleSheet("      height: 50px;\n"
"     width: 200px;\n"
"      box-sizing: border-box;\n"
"     background-color: white;\n"
"      border-radius: 5px;\n"
"     font-weight: bold;\n"
"")
        self.add_addMealButton.setObjectName("add_addMealButton")
        self.horizontalLayout_11.addWidget(self.add_addMealButton)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem21)
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        self.verticalLayout_6.setStretch(1, 2)
        self.verticalLayout_6.setStretch(3, 3)
        self.verticalLayout_6.setStretch(4, 1)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.verticalLayout_7.addWidget(self.widget_22)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.verticalLayout.addLayout(self.verticalLayout_8)
        self.stackedWidgetMain.addWidget(self.addPage)
        self.horizontalLayout_4.addWidget(self.stackedWidgetMain)
        self.horizontalLayout_9.addWidget(self.widget_11)
        self.horizontalLayout_2.addWidget(self.mainWidget)

        self.retranslateUi(Main)
        self.stackedWidgetMain.setCurrentIndex(3)
        self.stackedWidgetMeal.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "Dialog"))
        self.mainButton.setText(_translate("Main", "Главная"))
        self.mealButton.setText(_translate("Main", "Приемы пищи"))
        self.hungerButton.setText(_translate("Main", "Инт. голодание"))
        self.resultButton.setText(_translate("Main", "Результаты"))
        self.switchAccount.setText(_translate("Main", "Сменить аккаунт"))
        self.aboutButton.setText(_translate("Main", "О программе"))
        self.label_58.setText(_translate("Main", "Приемы пищи"))
        self.meal_breakButton.setText(_translate("Main", "Завтрак"))
        self.meal_dinnerButton.setText(_translate("Main", "Обед"))
        self.meal_emealButton.setText(_translate("Main", "Ужин"))
        self.meal_snackButton.setText(_translate("Main", "Перекусы"))
        self.label.setText(_translate("Main", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">Завтрак</span></p></body></html>"))
        self.breakName.setText(_translate("Main", "<html><head/><body><p>Введите завтрак</p></body></html>"))
        self.breakCalories.setText(_translate("Main", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">0 </span><span style=\" font-size:18pt;\">калории</span></p></body></html>"))
        self.breakProtein.setText(_translate("Main", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">0 </span><span style=\" font-size:18pt;\">белки</span></p></body></html>"))
        self.breakFat.setText(_translate("Main", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">0 </span><span style=\" font-size:18pt;\">жиры</span></p></body></html>"))
        self.breakCarbo.setText(_translate("Main", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">0 </span><span style=\" font-size:18pt;\">углеводы</span></p></body></html>"))
        self.label_3.setText(_translate("Main", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">Обед</span></p></body></html>"))
        self.dinnerName.setText(_translate("Main", "<html><head/><body><p>Введите обед</p></body></html>"))
        self.dinnerCalories.setText(_translate("Main", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">0 </span><span style=\" font-size:18pt;\">калории</span></p></body></html>"))
        self.dinnerProtein.setText(_translate("Main", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">0 </span><span style=\" font-size:18pt;\">белки</span></p></body></html>"))
        self.dinnerFat.setText(_translate("Main", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">0 </span><span style=\" font-size:18pt;\">жиры</span></p></body></html>"))
        self.dinnerCarbo.setText(_translate("Main", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">0 </span><span style=\" font-size:18pt;\">углеводы</span></p></body></html>"))
        self.label_4.setText(_translate("Main", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">Ужин</span></p></body></html>"))
        self.emealName.setText(_translate("Main", "<html><head/><body><p>Введите ужин</p></body></html>"))
        self.emealCalories.setText(_translate("Main", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">0 </span><span style=\" font-size:18pt;\">калории</span></p></body></html>"))
        self.emealProtein.setText(_translate("Main", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">0 </span><span style=\" font-size:18pt;\">белки</span></p></body></html>"))
        self.emealFat.setText(_translate("Main", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">0 </span><span style=\" font-size:18pt;\">жиры</span></p></body></html>"))
        self.emealCarbo.setText(_translate("Main", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">0 </span><span style=\" font-size:18pt;\">углеводы</span></p></body></html>"))
        self.label_5.setText(_translate("Main", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">Перекус</span></p></body></html>"))
        self.snackName.setText(_translate("Main", "<html><head/><body><p>Введите перекус</p></body></html>"))
        self.snackCalories.setText(_translate("Main", "0 калории"))
        self.snackProtein.setText(_translate("Main", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">0 </span><span style=\" font-size:18pt;\">белки</span></p></body></html>"))
        self.snackFat.setText(_translate("Main", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">0 </span><span style=\" font-size:18pt;\">жиры</span></p></body></html>"))
        self.snackCarbo.setText(_translate("Main", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">0 </span><span style=\" font-size:18pt;\">углеводы</span></p></body></html>"))
        self.label_84.setText(_translate("Main", "Интервальное голодание"))
        self.label_85.setText(_translate("Main", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">Следующий прием пищи через:</span></p></body></html>"))
        self.label_86.setText(_translate("Main", "<html><head/><body><p align=\"center\"><span style=\" font-size:48pt; font-weight:600;\">0</span></p></body></html>"))
        self.label_87.setText(_translate("Main", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">часов</span></p></body></html>"))
        self.pushButton_2.setText(_translate("Main", "PushButton"))
        self.label_107.setText(_translate("Main", "Результаты"))
        self.totalCalories.setText(_translate("Main", "<html><head/><body><p><span style=\" font-size:16pt;\">Калории:</span><span style=\" font-size:18pt; font-weight:600;\">0</span></p></body></html>"))
        self.totalProtein.setText(_translate("Main", "<html><head/><body><p><span style=\" font-size:16pt;\">Белки:</span><span style=\" font-size:18pt; font-weight:600;\">0</span></p></body></html>"))
        self.totalFat.setText(_translate("Main", "<html><head/><body><p><span style=\" font-size:16pt;\">Жиры:</span><span style=\" font-size:18pt; font-weight:600;\">0</span></p></body></html>"))
        self.totalCarbo.setText(_translate("Main", "<html><head/><body><p><span style=\" font-size:16pt;\">Углеводы:</span><span style=\" font-size:18pt; font-weight:600;\">0</span></p></body></html>"))
        self.label_6.setText(_translate("Main", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">Поздравляем!</span></p></body></html>"))
        self.label_7.setText(_translate("Main", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">Вы похудели на</span></p></body></html>"))
        self.congrats.setText(_translate("Main", "0"))
        self.label_8.setText(_translate("Main", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">килограмм</span></p></body></html>"))
        self.label_111.setText(_translate("Main", "Сегодня"))
        self.welcomeUser.setText(_translate("Main", "Здравствуйте, User"))
        self.PPLabel.setText(_translate("Main", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">0</span><span style=\" font-size:10pt;\">приёмов пищи</span></p></body></html>"))
        self.TrainingLabel.setText(_translate("Main", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">0</span><span style=\" font-size:10pt;\">тренировок</span></p></body></html>"))
        self.label_113.setText(_translate("Main", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">Цель</span></p><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">1200</span><span style=\" font-size:18pt;\"> калорий</span></p></body></html>"))
        self.label_114.setText(_translate("Main", "<html><head/><body><p align=\"center\">Белки</p></body></html>"))
        self.label_115.setText(_translate("Main", "<html><head/><body><p align=\"center\">Жиры</p></body></html>"))
        self.label_116.setText(_translate("Main", "<html><head/><body><p align=\"center\">Углеводы</p></body></html>"))
        self.label_117.setText(_translate("Main", "Приемы пищи"))
        self.label_2.setText(_translate("Main", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">Введите данные о пище</span></p></body></html>"))
        self.lineEdit.setPlaceholderText(_translate("Main", "Название"))
        self.add_calorieLine_.setPlaceholderText(_translate("Main", "Калории"))
        self.add_proteinLine_.setPlaceholderText(_translate("Main", "Белки"))
        self.add_fatLine_.setPlaceholderText(_translate("Main", "Жиры"))
        self.add_chLine_.setPlaceholderText(_translate("Main", "Углеводы"))
        self.add_addMealButton.setText(_translate("Main", "Добавить"))
import resources_rc
