# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'splash_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(800, 584)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 40, 160, 64))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(40, 110, 711, 271))
        self.frame.setStyleSheet("QFrame {\n"
"    border-radius: 15px;\n"
"    background-color: rgb(212, 212, 255);\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.PPLabel = QtWidgets.QLabel(self.frame)
        self.PPLabel.setGeometry(QtCore.QRect(30, 130, 91, 21))
        self.PPLabel.setObjectName("PPLabel")
        self.TrainingLabel = QtWidgets.QLabel(self.frame)
        self.TrainingLabel.setGeometry(QtCore.QRect(30, 150, 81, 21))
        self.TrainingLabel.setObjectName("TrainingLabel")
        self.CircularProgressBar = QtWidgets.QFrame(self.frame)
        self.CircularProgressBar.setGeometry(QtCore.QRect(560, 80, 120, 111))
        self.CircularProgressBar.setStyleSheet("QFrame{\n"
"    border-radius: 55px;\n"
"    background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0.749 rgba(0, 0, 0, 0), stop:0.75 rgba(255, 255, 255, 255));\n"
"}")
        self.CircularProgressBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.CircularProgressBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.CircularProgressBar.setObjectName("CircularProgressBar")
        self.CircularProgressBar_2 = QtWidgets.QFrame(self.CircularProgressBar)
        self.CircularProgressBar_2.setGeometry(QtCore.QRect(10, 10, 101, 91))
        self.CircularProgressBar_2.setStyleSheet("QFrame{\n"
"    border-radius: 45px;\n"
"    background-color: rgb(212, 212, 255);\n"
"}")
        self.CircularProgressBar_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.CircularProgressBar_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.CircularProgressBar_2.setObjectName("CircularProgressBar_2")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(50, 440, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.progressBar.setFont(font)
        self.progressBar.setStyleSheet("QProgressBar {\n"
"    background-color: white;\n"
"    border-radius: 10px;\n"
"    color: black;\n"
"    text-align: center;\n"
"  \n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"    border-radius: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(156, 164, 219, 255), stop:1 rgba(173, 200, 214, 255))\n"
"}")
        self.progressBar.setProperty("value", 100)
        self.progressBar.setObjectName("progressBar")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(80, 410, 47, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(370, 410, 47, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(640, 410, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.progressBar_2 = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_2.setGeometry(QtCore.QRect(320, 440, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.progressBar_2.setFont(font)
        self.progressBar_2.setStyleSheet("QProgressBar {\n"
"    background-color: white;\n"
"    border-radius: 10px;\n"
"    color: black;\n"
"    text-align: center;\n"
"  \n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"    border-radius: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(156, 164, 219, 255), stop:1 rgba(173, 200, 214, 255))\n"
"}")
        self.progressBar_2.setProperty("value", 50)
        self.progressBar_2.setObjectName("progressBar_2")
        self.progressBar_3 = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_3.setGeometry(QtCore.QRect(590, 440, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.progressBar_3.setFont(font)
        self.progressBar_3.setStyleSheet("QProgressBar {\n"
"    background-color: white;\n"
"    border-radius: 10px;\n"
"    color: black;\n"
"    text-align: center;\n"
"  \n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"    border-radius: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(156, 164, 219, 255), stop:1 rgba(173, 200, 214, 255))\n"
"}")
        self.progressBar_3.setProperty("value", 0)
        self.progressBar_3.setObjectName("progressBar_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Сегодня"))
        self.label.setText(_translate("MainWindow", "Здравствуйте, User"))
        self.PPLabel.setText(_translate("MainWindow", "0 приёмов пищи"))
        self.TrainingLabel.setText(_translate("MainWindow", "0 тренировок"))
        self.label_3.setText(_translate("MainWindow", "Белки"))
        self.label_4.setText(_translate("MainWindow", "Жиры"))
        self.label_5.setText(_translate("MainWindow", "Углеводы"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
